### ISSUE TITLE
can't refresh collectionViewFooterView location

### ISSUE THREAD

**Issue by liwancheng91** [Phelthas/LXMWaterfallLayout#1]
set UICollectionView layout

    let layout = LXMHeaderFooterFlowLayout()
    layout.collectionViewFooterHeight = 100

when reset   numberOfSections   and numberOfItemsInSection, then

    collectionView.reloadData()  

the collectionView's footerView does't change the location

**Comment by Phelthas** [comment]
Can you provide more details ？

**Comment by liwancheng91** [comment]
@Phelthas  Thanks for your reply
Here is the detail:
set the collectionView 

        let layout = LXMHeaderFooterFlowLayout()
        layout.sectionInset = UIEdgeInsets(top: 10, left: 10, bottom: 10, right: 10)
        layout.itemSize = CGSize(width: self.view.bounds.width-20, height: 50)
        layout.minimumLineSpacing = 10.0
        layout.minimumInteritemSpacing = 20.0
        layout.collectionViewHeaderHeight = 200
        layout.collectionViewFooterHeight = 100
        let collectionView = UICollectionView.init(frame: CGRect.zero, collectionViewLayout: layout)

set the numberOfSections,  numberOfItemsInSection

        func numberOfSections(in collectionView: UICollectionView) -> Int {
        if self.token != "" {
            return 3
        }
        return 1
    }
    
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        if self.token != "" {
            if section == 0 {
                return 2
            } else if section == 1 {
                return 5
            } else if section == 2 {
                return 1
            }
        }
        return 5
    }
at beginning ,  self.token = "",  after requests return  set self.token , and 

    collectionView.reloadData()

section and items has changed  , but the footerView at the origin location

the screenshots as follows :

begin
![2018-07-26 4 58 46](https://user-images.githubusercontent.com/1198948/43252584-7c5304ca-90f5-11e8-85a6-0b36e2410065.png)

after  reset  and reloadData
![2018-07-26 4 59 01](https://user-images.githubusercontent.com/1198948/43252617-868c2d18-90f5-11e8-9348-4b0022429338.png)

**Comment by Phelthas** [comment]
oh~I can reproduce it now，it is my bug,  the headerAttributes and footerAttributes are cached,  I will fix it soon!

**Comment by liwancheng91** [comment]
Thanks , I use swift4  ,install in   Manul  drag LXMWaterfallLayout.swift into project
if you have fixed it , you could send code to me, then i can test with you as soon as possible

**Comment by Phelthas** [comment]
![image](https://user-images.githubusercontent.com/8165982/43256467-5dd701b8-90ff-11e8-8f9a-56a195f9842f.png)
it is quite easy,  you just need to set the attributes to nil in `prepare()`

**Comment by liwancheng91** [comment]
# it works ， thanks very much

**Comment by Phelthas** [comment]
thank you for reporting this bug~
